language: node_js
services:
  - rabbitmq
node_js:
  - "9.1"
  - "node"
cache:
  directories:
  - "node_modules"
env:
  global:
    - CC_TEST_REPORTER_ID=584535b5281be348129a3e6f2054761470b903a9d1e7c49e0aeaaaf4c247c3be
    - NODE_ENV=test
    - ELASTIC_URL=127.0.0.1:9000
    - RABBITMQ_URL=amqp://0.0.0.0:5672
    - HOST_IP=127.0.0.1

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
